name: Deploy CV to pages
on: push

jobs:
  render-document:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile --font-path ./fonts cv.typ ./output/cv.pdf
      - uses: actions/upload-pages-artifact@v3
        with:
          path: output/
  deploy-pages:
    runs-on: ubuntu-latest
    needs: render-document
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/deploy-pages@v4
